name: "Komga"
version: 1.21.2
slug: "komga"
description: "Komga is a media server for your comics, mangas, BDs, magazines and eBooks."
url: https://komga.org/docs/introduction
arch:
  - amd64
  - aarch64
  - armhf
  - armv7
ports:
  25600/tcp: 25600
map:
  - type: addon_config
    read_only: false
  - type: media
    read_only: False
image: "ghcr.io/gotson/komga"
